import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../../core/value_objects/money.dart';
import '../../domain/revenue_summary.dart';
import '../bloc/admin_revenue_cubit.dart';

/// Admin revenue view (R6): the total revenue generated by completed events and
/// the money earned by all students, plus a per-completed-event breakdown.
///
/// Rendered as a tab body — owns its [AdminRevenueCubit] from the injected
/// [createCubit] factory and starts it with [AdminRevenueCubit.watch].
class AdminRevenueScreen extends StatelessWidget {
  const AdminRevenueScreen({
    required this.createCubit,
    required this.onOpenEvent,
    super.key,
  });

  final AdminRevenueCubit Function() createCubit;

  /// Opens the admin event-detail page when a completed-event card is tapped.
  final void Function(BuildContext context, String eventId) onOpenEvent;

  @override
  Widget build(BuildContext context) {
    return BlocProvider<AdminRevenueCubit>(
      create: (_) => createCubit()..watch(),
      child: BlocBuilder<AdminRevenueCubit, AdminRevenueState>(
        builder: (BuildContext context, AdminRevenueState state) {
          return switch (state) {
            RevenueLoading() =>
              const Center(child: CircularProgressIndicator()),
            RevenueFailure(:final String message) => Center(
                child: Padding(
                  padding: const EdgeInsets.all(24),
                  child: Text('Revenue could not be loaded.\n$message',
                      textAlign: TextAlign.center),
                ),
              ),
            RevenueLoaded(:final RevenueSummary summary) =>
              _RevenueView(summary: summary, onOpenEvent: onOpenEvent),
          };
        },
      ),
    );
  }
}

class _RevenueView extends StatelessWidget {
  const _RevenueView({required this.summary, required this.onOpenEvent});

  final RevenueSummary summary;
  final void Function(BuildContext context, String eventId) onOpenEvent;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return ListView(
      padding: const EdgeInsets.all(16),
      children: <Widget>[
        Row(
          children: <Widget>[
            Expanded(
              child: _HeadlineCard(
                label: 'Platform commission',
                value: summary.platformCommission,
                color: theme.colorScheme.primary,
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: _HeadlineCard(
                label: 'Earned by students',
                value: summary.studentsEarnedAll,
                color: Colors.greenAccent,
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              children: <Widget>[
                _line(theme, 'Completed events',
                    '${summary.completedEventCount}'),
                const SizedBox(height: 8),
                _line(theme, 'Distributed (completed events)',
                    '₹${summary.distributed.formatted}'),
                const SizedBox(height: 8),
                _line(theme, 'Event value (pay × slots)',
                    '₹${summary.revenue.formatted}'),
                const SizedBox(height: 8),
                _line(theme, 'Platform commission',
                    '₹${summary.platformCommission.formatted}'),
              ],
            ),
          ),
        ),
        const SizedBox(height: 20),
        Text('Completed events', style: theme.textTheme.titleMedium),
        const SizedBox(height: 8),
        if (summary.events.isEmpty)
          Text('No completed events yet.', style: theme.textTheme.bodySmall)
        else
          for (final EventRevenue e in summary.events)
            Card(
              margin: const EdgeInsets.only(bottom: 8),
              child: InkWell(
                onTap: () => onOpenEvent(context, e.eventId),
                borderRadius: BorderRadius.circular(12),
                child: Padding(
                  padding: const EdgeInsets.all(12),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Row(
                        children: <Widget>[
                          Expanded(
                            child: Text(e.title,
                                style: theme.textTheme.titleSmall),
                          ),
                          const Icon(Icons.chevron_right, size: 18),
                        ],
                      ),
                      const SizedBox(height: 2),
                      Text('${e.completedCount}/${e.slots} completed',
                          style: theme.textTheme.bodySmall),
                      const Divider(height: 16),
                      _line(theme, 'Event value', '₹${e.revenue.formatted}'),
                      const SizedBox(height: 4),
                      _line(theme, 'To students (net)',
                          '₹${e.studentEarnings.formatted}'),
                      const SizedBox(height: 4),
                      _line(theme, 'Platform (${e.commissionPercent}%)',
                          '₹${e.platformCommission.formatted}'),
                    ],
                  ),
                ),
              ),
            ),
      ],
    );
  }

  Widget _line(ThemeData theme, String label, String value) => Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Text(label, style: theme.textTheme.bodyMedium),
          Text(value,
              style: theme.textTheme.titleSmall
                  ?.copyWith(fontWeight: FontWeight.w700)),
        ],
      );
}

class _HeadlineCard extends StatelessWidget {
  const _HeadlineCard({
    required this.label,
    required this.value,
    required this.color,
  });

  final String label;
  final Money value;
  final Color color;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(label, style: theme.textTheme.bodySmall),
            const SizedBox(height: 8),
            Text('₹${value.formatted}',
                style: theme.textTheme.titleLarge
                    ?.copyWith(fontWeight: FontWeight.w800, color: color)),
          ],
        ),
      ),
    );
  }
}
